name: mela
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter_countdown_timer: ^4.1.0
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - lib/assets/icons/arrow_back_longer.png
    - lib/assets/icons/clock.png
    - lib/assets/icons/select_list.png
    - lib/assets/images/exit_image.png
    - lib/assets/icons/
    - lib/assets/images/
    - lib/assets/images/topics/
  fonts:
  - family: Asap
    fonts:
      - asset:   lib/assets/fonts/Asap/Asap-Thin.ttf
      - asset:   lib/assets/fonts/Asap/Asap-ExtraLight.ttf
      - asset:   lib/assets/fonts/Asap/Asap-Regular.ttf
      - asset:   lib/assets/fonts/Asap/Asap-Medium.ttf
      - asset:   lib/assets/fonts/Asap/Asap-SemiBold.ttf
      - asset:   lib/assets/fonts/Asap/Asap-Bold.ttf
      - asset:   lib/assets/fonts/Asap/Asap-ExtraBold.ttf
      - asset:   lib/assets/fonts/Asap/Asap-Black.ttf

  - family: Mulish
    fonts:
      - asset: lib/assets/fonts/Mulish/Mulish-Bold.ttf
      - asset: lib/assets/fonts/Mulish/Mulish-Regular.ttf
      - asset: lib/assets/fonts/Mulish/Mulish-SemiBold.ttf